- name: "Include distribution vars"
  include_vars: "{{ ansible_distribution }}.yml"

- name: Install package
  pacman:
   name: "{{ item }}"
   state: present
  with_items: "{{ packages }}"

- name: Update all package
  pacman:
   update_cache: yes
   upgrade: yes
