- name: Update all yum package
  yum:
   name: "*"
   state: latest

- name: Install epel-release
  yum:
   name: "epel-release"
   state: latest
  when: epel == true
 
- name: Ensure epel is not installed
  yum:
   name: "epel-release"
   state: absent
  when: epel == false

- name: Install a base package with yum
  yum:
   name: "{{ item }}"
   state: latest
  with_items:
     - vim
     - man
     - wget
     - bind-utils
     - curl
     - git
     - htop
     - pv
     - tmux
     - libselinux-python
     - dialog
     - bash-completion
     - zip
     - psmisc
     - libcgroup-tools
  when: epel == true

- name: Disable SELinux
  selinux: state=disabled
  when: "ansible_virtualization_type != 'openvz' and ansible_virtualization_type != 'lxc'"

- name: "Update all packages"
  yum:
    name: '*'
    state: latest
  when: update == true

- name: Install open-vm-tools for CentOS Distro
  yum:
    name: open-vm-tools
    state: latest
  when: ansible_virtualization_type == 'VMWare'
