- name: "Install epel-release"
  yum:
   name: "epel-release"
   state: "{{ package_state }}"
  when: epel | bool
 
- name: "Ensure epel is not installed"
  yum:
   name: "epel-release"
   state: absent
  when: not epel | bool

- name: "Install a base package with yum"
  yum:
   name: "{{ packages }}"
   state: "{{ package_state }}"
  when: epel | bool

- name: "Remove older kernel"
  shell: "package-cleanup --oldkernels --count={{ kernel_number }} -y"
  register: remove_kernels
  changed_when: '"No old kernels to remove" not in remove_kernels.stdout'
  failed_when: "remove_kernels.rc != 0"

- name: "Update all packages"
  yum:
    name: '*'
    state: latest
  when: update | bool

