- name: "Install epel-release"
  yum:
   name: "epel-release"
   state: present
  when: epel
 
- name: "Ensure epel is not installed"
  yum:
   name: "epel-release"
   state: absent
  when: not epel

- name: "Install a base package with yum"
  yum:
   name: "{{ item }}"
   state: present
  with_items: "{{ packages }}"
  when: epel

- name: "Update all packages"
  yum:
    name: '*'
    state: latest
  when: update

