- name: Update all yum package
  yum: name=* state=latest

- name: Install a base package with yum
  yum: name={{ item }} state=latest
  with_items:
     - epel-release
     - vim
     - man
     - wget
     - bind-utils
     - curl
     - git
     - htop
     - pv
     - tmux
     - libselinux-python
     - dialog
     - bash-completion
     - zip

#- name: Disable SELinux
#  selinux: state=disabled

- name: Modify SELinux in sysconfig
  replace: dest=/etc/sysconfig/selinux regexp='SELINUX\=[Ee]nforcing' replace='SELINUX\=disabled'

- name: Install open-vm-tools for CentOS Distro
  yum: name=open-vm-tools state=latest
  when: ansible_virtualization_type == 'VMWare'

- name: Customize vimrc RHEL Like
  template: src=vimrc_centos.j2 dest=/etc/vimrc
