---
# tasks file for common
- name: Include Debian File
  include: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Include CentOS File
  include: centos.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Add SSH Key
  authorized_key: 
     user: root 
     key: "{{ lookup('file', item) }}"
     state: present
  with_fileglob:
     - active_ssh_pub_keys/*.pub
  tags: ssh-key
