---
# tasks file for common
- name: "Include tasks"
  include: "{{ ansible_distribution }}.yml"

- name: "Set timezone"
  timezone:
    name: "{{ system_timezone }}"
  when: system_timezone is defined

- name: Create some users
  user:
    name: "{{ item.key }}"
    state: present
    groups: "{{ item.value.groups }}"
    shell: "{{ item.value.shell | default('/bin/bash') }}"
  with_dict: "{{ users }}"
  when: users is defined

- name: "Include ssh"
  include: ssh.yml
  when: ssh_keys is defined
 
- name: "Include virt"
  include: virt.yml
  when: ansible_virtualization_role == "guest" and manage_virt_guest == true
