---
# tasks file for common
- name: "Include distribution vars"
  include_vars: "{{ ansible_distribution }}.yml"

- name: "Include tasks"
  include: "{{ ansible_distribution }}.yml"

- name: "Include ssh"
  include: ssh.yml
  when: ssh_keys is defined
 
- name: Create some users
  user:
    name: "{{ item.key }}"
    state: present
    groups: "{{ item.value.groups }}"
  with_dict: "{{ users }}"
  when: users is defined
