---
# tasks file for common
- name: Include Debian File
  include: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Include CentOS File
  include: centos.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Add SSH Key
  authorized_key: 
     useri: root 
     key: "{{ item }}"
  with_fileglob:
     - files/active_ssh_pub_keys/*.pub
  tags: ssh-key
